# Generated by Django 5.0.2 on 2024-04-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(),
        ),
    ]
